// Copyright (C) 1991-2009 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 222 10/21/2009)
// Created on Fri Jun 23 09:25:37 2017

UartRX8N1 UartRX8N1_inst
(
	.clkIN(clkIN_sig) ,	// input  clkIN_sig
	.nResetIN(nResetIN_sig) ,	// input  nResetIN_sig
	.rxIN(rxIN_sig) ,	// input  rxIN_sig
	.dataOUT(dataOUT_sig) ,	// output [7:0] dataOUT_sig
	.doneOUT(doneOUT_sig) 	// output  doneOUT_sig
);

defparam UartRX8N1_inst.clkFreq = 48000000;
defparam UartRX8N1_inst.baudRate = 57600;
